
[functions.criar-usuario]
enabled = true
verify_jwt = true
import_map = "./functions/criar-usuario/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/criar-usuario/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/criar-usuario/*.html" ]

[functions.inscrever-veste-phenix]
enabled = true
verify_jwt = false
import_map = "./functions/inscrever-veste-phenix/deno.json"
entrypoint = "./functions/inscrever-veste-phenix/index.ts"

[functions.agenda-tecnico-ics]
enabled = true
verify_jwt = false
import_map = "./functions/agenda-tecnico-ics/deno.json"
entrypoint = "./functions/agenda-tecnico-ics/index.ts"

[functions.agenda-geral-ics]
enabled = true
verify_jwt = false
import_map = "./functions/agenda-geral-ics/deno.json"
entrypoint = "./functions/agenda-geral-ics/index.ts"
