import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import nodemailer from 'npm:nodemailer@7.0.11';

declare const EdgeRuntime: { waitUntil(promise: Promise<unknown>): void };
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const cnpjValido=(c:string)=>{if(!/^\d{14}$/.test(c)||/^(\d)\1+$/.test(c))return false;const calc=(n:number)=>{const p=n===12?[5,4,3,2,9,8,7,6,5,4,3,2]:[6,5,4,3,2,9,8,7,6,5,4,3,2];const r=p.reduce((s,x,i)=>s+(+c[i]*x),0)%11;return r<2?0:11-r};return calc(12)===+c[12]&&calc(13)===+c[13]};
const cpfValido=(c:string)=>{if(!/^\d{11}$/.test(c)||/^(\d)\1+$/.test(c))return false;const dig=(n:number)=>{let s=0;for(let i=0;i<n;i++)s+=Number(c[i])*(n+1-i);const r=(s*10)%11;return r===10?0:r};return dig(9)===Number(c[9])&&dig(10)===Number(c[10])};
const numeroAleatorio=()=>{const limite=Math.floor(0x100000000/100000)*100000;let valor;do{valor=crypto.getRandomValues(new Uint32Array(1))[0]}while(valor>=limite);return valor%100000};

async function enviarConfirmacao(db:ReturnType<typeof createClient>,data:{id:string;numero_sorte:number;nome_completo:string;email:string}){
 const resendKey=Deno.env.get('RESEND_API_KEY');const smtpUsuario=Deno.env.get('PROMO_SMTP_USUARIO');const smtpSenha=Deno.env.get('PROMO_SMTP_SENHA');const remetente=Deno.env.get('PROMO_FROM_EMAIL')||smtpUsuario;const nomeRemetente=Deno.env.get('PROMO_FROM_NAME')||'Promoção Veste Phenix 30 anos';
 if(!remetente||(!resendKey&&(!smtpUsuario||!smtpSenha))){await db.from('promocao_veste_phenix_30_anos').update({email_status:'aguardando_configuracao'}).eq('id',data.id);return}
 try{await db.from('promocao_veste_phenix_30_anos').update({email_status:'enviando',email_tentativas:1,email_ultimo_erro:null}).eq('id',data.id);const numero=String(data.numero_sorte).padStart(5,'0');const assunto=`Seu número da sorte Phenix 30 anos: ${numero}`;const html=`<div style="font-family:Arial;background:#062d55;padding:36px;color:#fff"><div style="max-width:620px;margin:auto;background:#fff;color:#123653;border-radius:18px;overflow:hidden"><div style="padding:30px;background:linear-gradient(120deg,#0b5687,#062846);color:#fff"><b style="color:#f4b13b;letter-spacing:3px">VESTE PHENIX • 30 ANOS</b><h1>Olá, ${esc(data.nome_completo)}!</h1></div><div style="padding:34px;text-align:center"><p>Sua inscrição foi confirmada. Seu número da sorte é:</p><div style="font-size:72px;font-weight:bold;color:#d78a19;letter-spacing:8px">${numero}</div><p>Guarde este e-mail. A apuração seguirá o regulamento oficial com base na Loteria Federal.</p></div></div></div>`;if(smtpUsuario&&smtpSenha){const transporte=nodemailer.createTransport({host:'smtp.gmail.com',port:465,secure:true,auth:{user:smtpUsuario,pass:smtpSenha},connectionTimeout:15000,socketTimeout:20000});await transporte.sendMail({from:{name:nomeRemetente,address:remetente},to:data.email,subject:assunto,html})}else{const er=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${resendKey}`,'Content-Type':'application/json'},body:JSON.stringify({from:remetente,to:[data.email],subject:assunto,html})});if(!er.ok)throw new Error(`Serviço de e-mail respondeu ${er.status}`)}await db.from('promocao_veste_phenix_30_anos').update({email_status:'enviado',email_confirmacao_enviado_em:new Date().toISOString(),email_ultimo_erro:null}).eq('id',data.id)
 }catch(e){console.error('Falha no e-mail',e);await db.from('promocao_veste_phenix_30_anos').update({email_status:'falhou',email_ultimo_erro:String(e).slice(0,500)}).eq('id',data.id)}
}

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({ok:false,mensagem:'Método não permitido.'},405);
 try{const b=await req.json();const cpf=String(b.cpf||'').replace(/\D/g,'');const cnpj=String(b.cnpj||'').replace(/\D/g,'');const modoTeste=Deno.env.get('PROMO_MODO_TESTE')==='true';
  if(!modoTeste&&Deno.env.get('PROMO_INSCRICOES_ATIVAS')!=='true')return json({ok:false,mensagem:'As inscrições ainda não estão abertas.'},403);const agora=Date.now();if(!modoTeste&&(agora<Date.parse('2026-10-06T00:00:00-03:00')||agora>Date.parse('2026-10-08T23:59:59-03:00')))return json({ok:false,mensagem:'Inscrição fora do período oficial da promoção.'},403);if(!b.maior_18||!b.aceite_regulamento||!b.aceite_privacidade)return json({ok:false,mensagem:'Aceites obrigatórios não confirmados.'},400);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(b.email||'')))return json({ok:false,mensagem:'E-mail inválido.'},400);
  if(!cpfValido(cpf))return json({ok:false,mensagem:'CPF inválido.'},400);if(!cnpjValido(cnpj))return json({ok:false,mensagem:'CNPJ inválido.'},400);const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
  const payload={nome_completo:String(b.nome_completo||'').trim(),cpf,email:String(b.email||'').trim().toLowerCase(),telefone:String(b.telefone||'').trim(),empresa:String(b.empresa||'').trim(),cnpj,cargo:String(b.cargo||'').trim(),cidade:String(b.cidade||'').trim(),uf:String(b.uf||'').toUpperCase(),segmento:String(b.segmento||''),relacao_phenix:String(b.relacao_phenix||''),maior_18:true,aceite_regulamento:true,aceite_privacidade:true,aceite_marketing:!!b.aceite_marketing,origem:modoTeste?'formulario_teste':'formulario_web'};
  let data,error;for(let tentativa=0;tentativa<12;tentativa++){const resultado=await db.from('promocao_veste_phenix_30_anos').insert({...payload,numero_sorte:numeroAleatorio()}).select('id,numero_sorte,nome_completo,email').single();data=resultado.data;error=resultado.error;if(!error)break;if(error.code!=='23505')throw error;const {data:cpfConcorrente}=await db.from('promocao_veste_phenix_30_anos').select('id').eq('cpf',cpf).maybeSingle();if(cpfConcorrente)return json({ok:false,mensagem:'Este CPF já possui uma inscrição e um número da sorte.'},409)}if(error||!data)throw new Error('Não foi possível reservar um número da sorte único.');
  EdgeRuntime.waitUntil(enviarConfirmacao(db,data));return json({ok:true,numero_sorte:data.numero_sorte},201)
 }catch(e){console.error(e);return json({ok:false,mensagem:'Não foi possível concluir a inscrição agora.'},500)}});
