import React from 'react';
import { supabase } from './supabaseClient';
import './promocao-publica.css';

// Ajustar aqui na abertura oficial (este projeto não usa .env para flags de build).
const publicado = false;
const modoTeste = true;
const REGULAMENTO_URL = '/regulamento.pdf';

const inicial={nome_completo:'',cpf:'',email:'',telefone:'',empresa:'',cnpj:'',cargo:'',cidade:'',uf:'',segmento:'',relacao_phenix:'',maior_18:false,aceite_regulamento:false,aceite_privacidade:false,aceite_marketing:false};
const ordem=['nome_completo','cpf','email','telefone','empresa','cnpj','cargo','cidade','uf','segmento','relacao_phenix','maior_18','aceite_regulamento','aceite_privacidade'];
const dig=v=>String(v||'').replace(/\D/g,'');
const cpfMask=v=>dig(v).slice(0,11).replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d{1,2})$/,'$1-$2');
const cnpjMask=v=>dig(v).slice(0,14).replace(/(\d{2})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1/$2').replace(/(\d{4})(\d{1,2})$/,'$1-$2');
const telMask=v=>{const d=dig(v).slice(0,11);if(d.length<=2)return d?`(${d}`:'';if(d.length<=3)return`(${d.slice(0,2)}) ${d.slice(2)}`;if(d.length<=7)return`(${d.slice(0,2)}) ${d.slice(2,3)} ${d.slice(3)}`;return`(${d.slice(0,2)}) ${d.slice(2,3)} ${d.slice(3,7)}-${d.slice(7)}`};
const cpfOk=v=>{const c=dig(v);if(c.length!==11||/^(\d)\1+$/.test(c))return false;const f=n=>{let s=0;for(let i=0;i<n;i++)s+=+c[i]*(n+1-i);const r=s*10%11;return r===10?0:r};return f(9)===+c[9]&&f(10)===+c[10]};
const cnpjOk=v=>{const c=dig(v);if(c.length!==14||/^(\d)\1+$/.test(c))return false;const f=n=>{const p=n===12?[5,4,3,2,9,8,7,6,5,4,3,2]:[6,5,4,3,2,9,8,7,6,5,4,3,2],r=p.reduce((s,x,i)=>s+(+c[i]*x),0)%11;return r<2?0:11-r};return f(12)===+c[12]&&f(13)===+c[13]};
const mensagens=f=>{const e={};if(f.nome_completo.trim().split(/\s+/).filter(x=>x.length>=2).length<2)e.nome_completo='Informe nome e sobrenome.';if(!dig(f.cpf))e.cpf='Informe o CPF.';else if(!cpfOk(f.cpf))e.cpf='CPF inválido. Confira os 11 números.';if(!f.email.trim())e.email='Informe o e-mail.';else if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(f.email))e.email='Informe um e-mail válido, incluindo @ e domínio.';if(!dig(f.telefone))e.telefone='Informe o telefone/WhatsApp.';else if(dig(f.telefone).length!==11)e.telefone='Informe DDD e celular com 11 números.';if(!f.empresa.trim())e.empresa='Informe a empresa.';if(!dig(f.cnpj))e.cnpj='Informe o CNPJ.';else if(!cnpjOk(f.cnpj))e.cnpj='CNPJ inválido. Confira os 14 números.';if(!f.cargo.trim())e.cargo='Informe o cargo ou função.';if(!f.cidade.trim())e.cidade='Informe a cidade.';if(!f.uf)e.uf='Selecione o estado.';if(!f.segmento)e.segmento='Selecione o segmento.';if(!f.relacao_phenix)e.relacao_phenix='Selecione a relação com a Phenix.';if(!f.maior_18)e.maior_18='Confirme que possui 18 anos ou mais.';if(!f.aceite_regulamento)e.aceite_regulamento='Leia e aceite o regulamento.';if(!f.aceite_privacidade)e.aceite_privacidade='Aceite a política de privacidade.';return e};
async function mensagemDaFuncao(error,data){if(data?.mensagem)return data.mensagem;try{const resposta=error?.context;if(resposta&&typeof resposta.json==='function'){const corpo=await resposta.json();if(corpo?.mensagem)return corpo.mensagem}}catch{/* resposta sem JSON */}return'Não foi possível concluir. Tente novamente.'}

export default function FormularioPromocao(){
 const[f,setF]=React.useState(inicial),[erros,setErros]=React.useState({}),[status,setStatus]=React.useState(''),[numeros,setNumeros]=React.useState(null);const refs=React.useRef({});
 const set=(k,v)=>{setF(x=>({...x,[k]:v}));setErros(x=>{const n={...x};delete n[k];return n})},ref=k=>el=>{if(el)refs.current[k]=el},erro=k=>erros[k]?<span className="campo-erro">{erros[k]}</span>:null,cls=k=>erros[k]?'invalido':'';
 const input=(k,label,props={})=>{const{mask,...htmlProps}=props;return <label>{label}<input ref={ref(k)} className={cls(k)} aria-invalid={!!erros[k]} value={f[k]} onChange={e=>set(k,mask?mask(e.target.value):e.target.value)} {...htmlProps}/>{erro(k)}</label>};
 const select=(k,label,opcoes)=><label>{label}<select ref={ref(k)} className={cls(k)} aria-invalid={!!erros[k]} value={f[k]} onChange={e=>set(k,e.target.value)}><option value="">Selecione</option>{opcoes.map(x=><option key={x}>{x}</option>)}</select>{erro(k)}</label>;
 const check=(k,conteudo,opcional=false)=><div className={`check-item ${erros[k]?'invalido':''}`}><label><input ref={opcional?undefined:ref(k)} type="checkbox" checked={f[k]} onChange={e=>set(k,e.target.checked)}/>{conteudo}</label>{erro(k)}</div>;
 async function enviar(ev){ev.preventDefault();setStatus('');const e=mensagens(f);setErros(e);const primeiro=ordem.find(k=>e[k]);if(primeiro){setTimeout(()=>{refs.current[primeiro]?.focus();refs.current[primeiro]?.scrollIntoView({behavior:'smooth',block:'center'})});return}if(!publicado&&!modoTeste)return setStatus('Inscrições ainda não abertas.');setStatus('Enviando inscrição…');const{data,error}=await supabase.functions.invoke('inscrever-veste-phenix',{body:{...f,cpf:dig(f.cpf),cnpj:dig(f.cnpj),telefone:dig(f.telefone)}});if(error||!data?.ok){const mensagem=await mensagemDaFuncao(error,data);if(mensagem.toLowerCase().includes('cpf')){setErros({cpf:mensagem});setStatus('');setTimeout(()=>refs.current.cpf?.focus())}else setStatus(mensagem);return}setNumeros(data.numeros_sorte.map(n=>String(n).padStart(5,'0')).sort())}
 if(numeros)return <main className="promo-publica success"><div className="confete">✦ ✧ ✦</div><img className="marca-30" src="/phenix-30-anos-branco-transparente.png?v=20260804-12" alt="Phenix - Tecendo Facilidades"/><p className="eyebrow">INSCRIÇÃO CONFIRMADA</p><h1>Seus 10 números da sorte são</h1><div className="numeros-grid">{numeros.map(n=><span key={n} className="numero-chip">{n}</span>)}</div><p>Guarde estes números.</p></main>;
 const ufs='AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO'.split(' '),segmentos=['Papel e celulose','Tissue','Papel cartão','Embalagens','Reciclagem','Tratamento de efluentes','Engrossadores','Mineração','Outro segmento industrial'];
 return <div className="promo-publica"><header><img className="marca-30-cabecalho" src="/phenix-30-anos-transparente.png?v=20260804-2" alt="Phenix 30 anos - Tecendo Facilidades"/><span>VESTE PHENIX</span></header><main className="layout"><section className="hero"><p className="eyebrow">VESTE PHENIX</p><h1>Uma experiência que vai levar você mais alto.</h1><p>Cadastre-se para concorrer à Experiência Técnica Comemorativa Phenix 30 anos no Rio Grande do Sul.</p><div className="marca-30-hero"><img src="/phenix-30-anos-branco-transparente.png?v=20260804-2" alt="Phenix 30 anos - Tecendo Facilidades"/></div><p className="periodo">Participações: 06 a 08 de outubro de 2026</p></section><section className="card"><h2>Faça sua inscrição</h2><p>Um cadastro por CPF, com 10 números da sorte. Todos os campos são obrigatórios.</p>{!publicado&&<div className="aviso">{modoTeste?'AMBIENTE DE TESTE — os dados serão apagados antes da abertura oficial.':'Inscrições ainda não abertas.'}</div>}<form onSubmit={enviar} noValidate>{input('nome_completo','Nome completo')}<div className="grid">{input('cpf','CPF',{mask:cpfMask,inputMode:'numeric'})}{input('email','E-mail corporativo',{type:'email'})}{input('telefone','WhatsApp',{mask:telMask,inputMode:'tel'})}{input('empresa','Empresa')}{input('cnpj','CNPJ',{mask:cnpjMask,inputMode:'numeric'})}{input('cargo','Cargo/função')}{input('cidade','Cidade')}{select('uf','UF',ufs)}{select('segmento','Segmento',segmentos)}{select('relacao_phenix','Relação com a Phenix',['Cliente','Ex-cliente','Parceiro','Empresa convidada'])}</div><div className="checks">{check('maior_18','Declaro ter 18 anos ou mais.')}{check('aceite_regulamento',<>Li e aceito o <a href={REGULAMENTO_URL} target="_blank">regulamento</a>.</>)}{check('aceite_privacidade','Aceito a política de privacidade e o tratamento de dados para execução da promoção.')}{check('aceite_marketing','Quero receber novidades da Phenix (opcional).',true)}</div>{status&&<p className="erro">{status}</p>}<button disabled={status==='Enviando inscrição…'}>{status==='Enviando inscrição…'?'Enviando…':'Gerar meus 10 números da sorte'}</button></form></section></main><footer>Promoção sujeita à autorização da SPA/MF.</footer></div>;
}
