import { useEffect, useState } from "react";
import * as XLSX from "xlsx";
import { supabase } from "./supabaseClient";

export default function PromocaoVestePhenix() {
  const [inscricoes,setInscricoes]=useState([]),[erro,setErro]=useState(""),[carregando,setCarregando]=useState(true),[numero,setNumero]=useState(""),[data,setData]=useState("2026-10-10"),[resultado,setResultado]=useState(null);
  async function carregar(){setCarregando(true);const {data:d,error}=await supabase.from("promocao_veste_phenix_30_anos").select("*").order("numero_sorte");setInscricoes(d||[]);setErro(error?"Não foi possível carregar as inscrições.":"");setCarregando(false)}
  // eslint-disable-next-line react-hooks/set-state-in-effect -- carregamento inicial da lista
  useEffect(()=>{carregar()},[]);
  function exportar(){const linhas=inscricoes.map(i=>({"Número da sorte":String(i.numero_sorte).padStart(5,"0"),Nome:i.nome_completo,CPF:i.cpf,"E-mail":i.email,WhatsApp:i.telefone,Empresa:i.empresa,CNPJ:i.cnpj,Cargo:i.cargo,Cidade:i.cidade,UF:i.uf,Segmento:i.segmento,"Relação Phenix":i.relacao_phenix,Status:i.status,"Inscrição em":i.criado_em,"E-mail enviado em":i.email_confirmacao_enviado_em||""}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(linhas),"Inscrições");XLSX.writeFile(wb,`veste_phenix_30_anos_${new Date().toISOString().slice(0,10)}.xlsx`)}
  async function apurar(){if(!/^\d+$/.test(numero))return setErro("Informe somente os algarismos do resultado da Loteria Federal.");if(!confirm("Esta ação registra oficialmente a apuração. Deseja continuar?"))return;const {data:r,error}=await supabase.rpc("apurar_veste_phenix",{p_numero_loteria:Number(numero),p_data_extracao:data,p_concurso:null,p_fonte_url:null});if(error)return setErro(error.message);setResultado(r?.[0]);setErro("");await carregar()}
  return <section className="painel-admin promocao-admin"><div className="secao-contexto"><div><h2>Veste Phenix — 30 anos</h2><p>Inscrições, auditoria, exportação e apuração da promoção sazonal.</p></div></div><div className="admin-bloco"><div className="promocao-resumo"><strong>{inscricoes.length}</strong><span>inscrições totais</span><strong>{inscricoes.filter(i=>i.status==='valida').length}</strong><span>válidas</span><button type="button" onClick={exportar} disabled={!inscricoes.length}>Exportar Excel</button></div>{erro&&<p className="mensagem-erro">{erro}</p>}{carregando?<p>Carregando…</p>:<div className="promocao-tabela-wrap"><table><thead><tr><th>Nº</th><th>Participante</th><th>Empresa</th><th>CPF</th><th>Data/hora</th><th>Status</th></tr></thead><tbody>{inscricoes.map(i=><tr key={i.id}><td><b>{String(i.numero_sorte).padStart(5,'0')}</b></td><td>{i.nome_completo}<small>{i.email}</small></td><td>{i.empresa}</td><td>{i.cpf.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/,'$1.$2.$3-$4')}</td><td>{new Date(i.criado_em).toLocaleString('pt-BR')}</td><td>{i.status}</td></tr>)}</tbody></table></div>}</div><div className="admin-bloco"><h3>Apuração pela Loteria Federal</h3><p>O sistema seleciona a menor diferença absoluta; havendo empate, vence a inscrição válida mais antiga.</p><div className="promocao-apuracao"><label>Número apurado<input value={numero} inputMode="numeric" onChange={e=>setNumero(e.target.value.replace(/\D/g,''))}/></label><label>Data da extração<input type="date" value={data} onChange={e=>setData(e.target.value)}/></label><button type="button" onClick={apurar}>Realizar apuração</button></div>{resultado&&<div className="promocao-vencedor"><b>Contemplado: {resultado.nome_completo}</b><span>Número {String(resultado.numero_sorte).padStart(5,'0')} • diferença {resultado.diferenca}</span></div>}</div></section>
}
