alter table public.rota_clientes
	add column if not exists aviso_whatsapp_status text;

update public.rota_clientes
set aviso_whatsapp_status = 'ENVIADO_ABERTURA'
where aviso_whatsapp_em is not null
	and (aviso_whatsapp_status is null or aviso_whatsapp_status = '');

create table if not exists public.rota_clientes_whatsapp_historico (
	id bigint generated by default as identity primary key,
	rota_cliente_id bigint not null references public.rota_clientes(id) on delete cascade,
	rota_id bigint not null references public.rotas(id) on delete cascade,
	cliente_id bigint not null references public.clientes(id) on delete cascade,
	criado_por uuid references auth.users(id),
	evento text not null,
	status text not null,
	telefone text,
	mensagem text,
	cliente_nome text,
	enviado_em timestamptz not null,
	criado_em timestamptz not null default timezone('utc', now())
);

alter table public.rota_clientes_whatsapp_historico enable row level security;

drop policy if exists "hist_whatsapp_select_participantes"
on public.rota_clientes_whatsapp_historico;

create policy "hist_whatsapp_select_participantes"
on public.rota_clientes_whatsapp_historico
for select
to authenticated
using (
	public.radar_perfil_atual_tipo() = 'admin'
	or exists (
		select 1
		from public.rotas r
		where r.id = rota_id
			and (r.criado_por = auth.uid() or r.usuario_responsavel = auth.uid())
	)
);

drop policy if exists "hist_whatsapp_insert_participantes"
on public.rota_clientes_whatsapp_historico;

create policy "hist_whatsapp_insert_participantes"
on public.rota_clientes_whatsapp_historico
for insert
to authenticated
with check (
	criado_por = auth.uid()
	and (
		public.radar_perfil_atual_tipo() = 'admin'
		or exists (
			select 1
			from public.rotas r
			where r.id = rota_id
				and (r.criado_por = auth.uid() or r.usuario_responsavel = auth.uid())
		)
	)
);
