-- BASELINE: tabelas criadas direto no Supabase Studio antes deste projeto
-- adotar migrations versionadas (perfis, clientes, clientes_geolocalizacao,
-- rotas, rota_clientes, visitas, importacoes, amostras_phenix e a legada
-- perfis_usuarios). Ate agora nenhuma migration do repositorio as criava,
-- o que tornava impossivel auditar por codigo se RLS estava habilitada e
-- corretamente configurada nelas -- foi exatamente essa lacuna que escondeu
-- por um tempo as policies "libera tudo" corrigidas em
-- 20260825130000_seguranca_clientes_perfis_rls.sql.
--
-- Reconstruido em 2026-08-25 via introspeccao direta do banco remoto
-- (`supabase db query --linked` contra information_schema/pg_catalog, sem
-- Docker instalado nesta maquina). Todas as instrucoes sao idempotentes
-- (`if not exists` / drop-then-create de policy): como as tabelas ja
-- existem em producao, `create table if not exists` e um no-op ali e so
-- passa a valer se este schema for recriado do zero (ambiente novo).
--
-- Nao e uma copia 1:1 de pg_dump (comentarios de coluna, ownership de
-- sequence etc. podem faltar) -- o objetivo e fechar o gap de auditoria de
-- RLS/policies, que e a parte que importa para seguranca de dados.

-- ============================================================
-- perfis
-- ============================================================
create table if not exists public.perfis (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  nome character varying(150),
  email character varying(150),
  tipo_perfil character varying(30) not null,
  codigo_representante character varying(20),
  ativo boolean default true,
  created_at timestamp default now(),
  piloto_comissoes boolean not null default false,
  log_acesso_ativo boolean not null default false,
  constraint perfis_user_id_unique unique (user_id)
);

alter table public.perfis enable row level security;

drop policy if exists "perfis_select" on public.perfis;
create policy "perfis_select" on public.perfis for select to authenticated using (true);

drop policy if exists "usuario_logado_pode_ler_perfis" on public.perfis;
create policy "usuario_logado_pode_ler_perfis" on public.perfis for select to authenticated using (true);

drop policy if exists "perfis_insert_admin" on public.perfis;
create policy "perfis_insert_admin" on public.perfis for insert to authenticated
with check (exists (select 1 from public.perfis p where p.user_id = auth.uid() and p.tipo_perfil = 'admin' and p.ativo = true));

drop policy if exists "perfis_update_admin" on public.perfis;
create policy "perfis_update_admin" on public.perfis for update to authenticated
using (exists (select 1 from public.perfis p where p.user_id = auth.uid() and p.tipo_perfil = 'admin' and p.ativo = true))
with check (exists (select 1 from public.perfis p where p.user_id = auth.uid() and p.tipo_perfil = 'admin' and p.ativo = true));

-- ============================================================
-- clientes
-- ============================================================
create table if not exists public.clientes (
  id bigint generated always as identity primary key,
  codigo_cliente character varying(20),
  cliente character varying(255) not null,
  endereco character varying(255),
  numero character varying(50),
  bairro character varying(150),
  cidade character varying(150),
  uf character varying(2),
  cep character varying(20),
  endereco_completo text,
  telefone character varying(50),
  whatsapp character varying(50),
  email character varying(255),
  tipo character varying(50) default 'CLIENTE',
  prioridade character varying(20) default 'MEDIA',
  status character varying(30) default 'ATIVO',
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  ultima_visita timestamp,
  observacao text,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  codigo_representante character varying(20),
  geocodificado_em timestamp,
  erro_geocodificacao text,
  constraint uq_clientes_codigo_cliente unique (codigo_cliente)
);

alter table public.clientes enable row level security;

-- Policies de select/delete/insert/update admin corrigidas em
-- 20260825130000_seguranca_clientes_perfis_rls.sql; nao repetidas aqui
-- para nao mascarar aquela migration como fonte da verdade.

drop policy if exists "usuarios_logados_podem_inserir_clientes" on public.clientes;
create policy "usuarios_logados_podem_inserir_clientes" on public.clientes for insert to authenticated with check (true);

drop policy if exists "usuarios_logados_podem_atualizar_clientes" on public.clientes;
create policy "usuarios_logados_podem_atualizar_clientes" on public.clientes for update to authenticated using (true) with check (true);

-- ============================================================
-- clientes_geolocalizacao (cache de geocodificacao, usado pela function geocodificar-clientes)
-- ============================================================
create table if not exists public.clientes_geolocalizacao (
  id bigint generated by default as identity primary key,
  codigo_cliente character varying(20) not null,
  endereco_chave text not null,
  latitude numeric,
  longitude numeric,
  geocodificado_em timestamp,
  erro_geocodificacao text,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  geolocalizacao_pendente boolean default true,
  constraint uk_clientes_geolocalizacao unique (codigo_cliente)
);

create index if not exists idx_clientes_geolocalizacao_codigo
  on public.clientes_geolocalizacao (codigo_cliente);

alter table public.clientes_geolocalizacao enable row level security;

drop policy if exists "usuarios_logados_podem_ler_geolocalizacao" on public.clientes_geolocalizacao;
create policy "usuarios_logados_podem_ler_geolocalizacao" on public.clientes_geolocalizacao for select to authenticated using (true);

drop policy if exists "usuarios_logados_podem_inserir_geolocalizacao" on public.clientes_geolocalizacao;
create policy "usuarios_logados_podem_inserir_geolocalizacao" on public.clientes_geolocalizacao for insert to authenticated with check (true);

drop policy if exists "usuarios_logados_podem_atualizar_geolocalizacao" on public.clientes_geolocalizacao;
create policy "usuarios_logados_podem_atualizar_geolocalizacao" on public.clientes_geolocalizacao for update to authenticated using (true) with check (true);

-- ============================================================
-- rotas
-- ============================================================
create table if not exists public.rotas (
  id bigint generated by default as identity primary key,
  nome character varying(255) not null,
  user_id uuid not null,
  status character varying(30) default 'ABERTA',
  data_rota date default current_date,
  created_at timestamp default now(),
  observacao text,
  iniciada_em timestamp,
  finalizada_em timestamp,
  criado_por uuid,
  usuario_responsavel uuid references auth.users (id)
);

create index if not exists idx_rotas_usuario_responsavel
  on public.rotas (usuario_responsavel);

alter table public.rotas enable row level security;

drop policy if exists "rotas_select" on public.rotas;
create policy "rotas_select" on public.rotas for select to authenticated using (true);

drop policy if exists "rotas_insert" on public.rotas;
create policy "rotas_insert" on public.rotas for insert to authenticated with check (true);

drop policy if exists "rotas_update" on public.rotas;
create policy "rotas_update" on public.rotas for update to authenticated using (true) with check (true);

drop policy if exists "rotas_delete" on public.rotas;
create policy "rotas_delete" on public.rotas for delete to authenticated using (true);

-- policy RESTRICTIVE "rotas_delete_restringe_finalizada" ja versionada em
-- 20260819120000_rotas_delete_restringe_finalizada.sql.

-- ============================================================
-- rota_clientes
-- ============================================================
create table if not exists public.rota_clientes (
  id bigint generated by default as identity primary key,
  rota_id bigint not null,
  cliente_id bigint not null,
  sequencia integer,
  visitado boolean default false,
  created_at timestamp default now(),
  status character varying(30) default 'PENDENTE',
  aviso_whatsapp_em timestamptz,
  aviso_whatsapp_por uuid,
  aviso_whatsapp_mensagem text,
  aviso_whatsapp_status text,
  data_prevista_visita date,
  horario_previsto_visita time,
  incluido_por uuid,
  motivo_cancelamento text
);

create index if not exists rota_clientes_rota_cliente_idx
  on public.rota_clientes (rota_id, cliente_id);
create index if not exists rota_clientes_data_prevista_visita_idx
  on public.rota_clientes (data_prevista_visita, status);

alter table public.rota_clientes enable row level security;

drop policy if exists "rota_clientes_select" on public.rota_clientes;
create policy "rota_clientes_select" on public.rota_clientes for select to authenticated using (true);

drop policy if exists "rota_clientes_insert" on public.rota_clientes;
create policy "rota_clientes_insert" on public.rota_clientes for insert to authenticated with check (true);

drop policy if exists "rota_clientes_update" on public.rota_clientes;
create policy "rota_clientes_update" on public.rota_clientes for update to authenticated using (true) with check (true);

drop policy if exists "rota_clientes_delete" on public.rota_clientes;
create policy "rota_clientes_delete" on public.rota_clientes for delete to authenticated using (true);

-- policy RESTRICTIVE "rota_clientes_delete_restringe_finalizada" ja
-- versionada em 20260819120000_rotas_delete_restringe_finalizada.sql.

-- ============================================================
-- visitas
-- ============================================================
create table if not exists public.visitas (
  id bigint generated always as identity primary key,
  cliente_id bigint not null references public.clientes (id),
  user_id uuid,
  tipo_visita character varying(50) default 'ROTA',
  status character varying(30) default 'REALIZADA',
  observacao text,
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  data_visita timestamp default now(),
  created_at timestamp default now()
);

alter table public.visitas enable row level security;

drop policy if exists "usuarios_logados_podem_ler_visitas" on public.visitas;
create policy "usuarios_logados_podem_ler_visitas" on public.visitas for select to authenticated using (true);

drop policy if exists "visitas_select_autenticado" on public.visitas;
create policy "visitas_select_autenticado" on public.visitas for select to authenticated using (true);

drop policy if exists "usuarios_logados_podem_inserir_visitas" on public.visitas;
create policy "usuarios_logados_podem_inserir_visitas" on public.visitas for insert to authenticated with check (true);

drop policy if exists "visitas_insert_autenticado" on public.visitas;
create policy "visitas_insert_autenticado" on public.visitas for insert to authenticated with check (user_id = auth.uid());

-- ============================================================
-- importacoes (historico de importacao de planilha Excel)
-- ============================================================
create table if not exists public.importacoes (
  id bigint generated always as identity primary key,
  nome_arquivo character varying(255),
  total_registros integer default 0,
  total_inseridos integer default 0,
  total_atualizados integer default 0,
  total_ignorados integer default 0,
  status character varying(30) default 'PROCESSADA',
  observacao text,
  user_id uuid,
  created_at timestamp default now()
);

alter table public.importacoes enable row level security;

drop policy if exists "importacoes_select_autenticado" on public.importacoes;
create policy "importacoes_select_autenticado" on public.importacoes for select to authenticated using (true);

-- policy de insert restrita a admin ja recriada (com
-- radar_perfil_atual_tipo()) em 20260825130000_seguranca_clientes_perfis_rls.sql.

-- ============================================================
-- amostras_phenix (espelho consultivo do GEACOMP/CIGAM, sync via service_role)
-- ============================================================
create table if not exists public.amostras_phenix (
  id bigint generated by default as identity primary key,
  id_amostra_oracle integer not null,
  cd_cliente text not null,
  nome_cliente text,
  cd_produto text,
  descricao_produto text,
  fornecedor_concorrente text,
  posicao text,
  maquina text,
  tempo_duracao_dias integer,
  cfm numeric,
  gramatura numeric,
  espessura numeric,
  tipo_papel text,
  tipo_amostra text,
  observacoes text,
  created_by text,
  created_at timestamp,
  updated_by text,
  updated_at timestamp,
  synced_at timestamp default now(),
  id_geacomp_origem bigint,
  chave_geacomp_origem text,
  sequencia_geacomp integer,
  status_geacomp text,
  comprimento numeric(12, 3),
  largura numeric(12, 3),
  modelo_concorrente text,
  constraint amostras_phenix_id_amostra_oracle_key unique (id_amostra_oracle),
  constraint amostras_phenix_status_geacomp_check check (
    status_geacomp is null or status_geacomp in ('EM_ANALISE', 'CONCLUIDO', 'IGNORADO')
  )
);

create index if not exists idx_amostras_phenix_cd_cliente on public.amostras_phenix (cd_cliente);
create index if not exists idx_amostras_phenix_tipo on public.amostras_phenix (tipo_amostra);

alter table public.amostras_phenix enable row level security;

-- policy de select condicionada a configuracoes_grupos.permite_menu_amostras
-- ja versionada em 20260825140000_amostras_phenix_rls_por_grupo.sql.

-- ============================================================
-- perfis_usuarios (LEGADO -- ver nota abaixo)
-- ============================================================
-- Tabela paralela a "perfis", usada apenas pela funcao legada
-- usuario_admin(). Tinha so 2 linhas em 2026-08-25 (perfis tem 12) e nao
-- possui trigger de sincronizacao com perfis -- ou seja, qualquer admin
-- criado depois da adocao da function criar-usuario nunca apareceu aqui.
-- As policies que dependiam de usuario_admin() ja foram trocadas para
-- radar_perfil_atual_tipo() (que le perfis, mantida em dia) em
-- 20260825130000_seguranca_clientes_perfis_rls.sql. Mantida aqui so para
-- nao quebrar usuario_admin() caso algo ainda dependa dela; considerar
-- descontinuar apos confirmar que nada mais a referencia.
create table if not exists public.perfis_usuarios (
  id bigint generated always as identity primary key,
  user_id uuid not null,
  nome character varying(150) not null,
  email character varying(255) not null,
  tipo character varying(30) not null default 'REPRESENTANTE',
  status character varying(30) not null default 'ATIVO',
  created_at timestamp default now(),
  updated_at timestamp default now()
);

alter table public.perfis_usuarios enable row level security;

drop policy if exists "perfis_select_proprio" on public.perfis_usuarios;
create policy "perfis_select_proprio" on public.perfis_usuarios for select to authenticated using (user_id = auth.uid());
